//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notDBEntities2 : DbContext
    {
        public notDBEntities2()
            : base("name=notDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<notAlbum> notAlbum { get; set; }
        public virtual DbSet<notResim> notResim { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
