//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notResim
    {
        public int resimID { get; set; }
        public string resimYol { get; set; }
        public int yukleyenID { get; set; }
        public int albumID { get; set; }
    
        public virtual notAlbum notAlbum { get; set; }
        public virtual user user { get; set; }
    }
}
