//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.notAlbum = new HashSet<notAlbum>();
            this.notResim = new HashSet<notResim>();
        }
    
        public int Id { get; set; }

        
        [Required(ErrorMessage = "{0} bos birakilmaz")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                           @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                           @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                           ErrorMessage = "Email adresi gecersiz")]
        public string user_mail { get; set; }

        [Required]
        [StringLength(32, MinimumLength = 8,ErrorMessage ="{0} minimum {2} karakter olmalidir")]
        public string user_pw { get; set; }

        [Required(ErrorMessage = "{0} bos birakilmaz")]
        public string user_adsoyad { get; set; }
        
        public string user_universite { get; set; }
        public string user_bolum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notAlbum> notAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notResim> notResim { get; set; }
    }
}
